import Head from 'next/head'
import { Inter } from '@next/font/google'
import { AppBar } from '../lib/components/general/AppBar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{
        backgroundImage: 'url(https://www.kindacode.com/wp-content/uploads/2022/05/green.jpeg)',
        width: '100vw',
        height: '100vh',
      }}>
        <AppBar />
      </main>
    </>
  )
}
